name: Testing

on: [push] 

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jpetrucciani/black-check@master
        with:
          path: "."