name: Testing

on: [push] 

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.10' 
      - uses: jpetrucciani/black-check@master
        with:
          path: "."
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
      - name: "Install dependencies"
        run: pip install numpy pytest matplotlib
      - name: "Run pytest"
        run: python -m pytest
      - name: "Install coverage"
        run: pip install coverage
      - name: "Run coverage"
        run: coverage run -m pytest
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ".coverage"
          retention-days: 1
  coverage_report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
      - name: "Install dependencies"
        run: pip install numpy pytest matplotlib
      - uses: actions/download-artifact@v3
        with:
          name: coverage  
          path: ".coverage"        
      - name: Display structure of downloaded files
        run: ls -R
      - name: "Install coverage"
        run: pip install coverage
      - name: "Run coverage report"
        run: coverage report
      - uses: actions/upload-artifact@v3
        with:
          name: coverage_xml
          path: "coverage.xml"
          retention-days: 14